### ISSUE TITLE
Model structure

### ISSUE THREAD

**Issue by rafaqz** [CliMA/Land#1]
Hi, it's great to see some more biophysical models in julia.

I've been putting this package together over the last year: https://github.com/rafaqz/Photosynthesis.jl as a rewrite of the MAESPA photosynthesis model. It may be useful to you at this stage, if not for direct use for structural ideas. Notably the parameters are a composable hierarchy instead of a single flat struct, and you can swap out any components for your own custom formulations, or use them in another package. 

Writing the package I was keen to explore how we could use shared libraries for biophysical formulations instead of rewriting formulations every time as has been common in the past. There are a _lot_ of Farquhar models implemented slightly differently in various Fortran libraries, but Julia can facilitate doing things differently.

Anyway, carry on! hopefully this added something useful to mix.

**Comment by cfranken** [comment]
Rafael,

We just started these efforts and will look at refactoring at a later stage anyhow. Your code looks very useful and it is great to see this in Julia, so much cleaner than anything else. How about staying in touch on this, we could leverage a lot (both of us), just shoot me an email cfranken"at"caltech.edu

**Comment by cfranken** [comment]
Rafael, we started with refactoring now and I "borrowed" a lot of your ideas in terms of abstractions. Let us know if you have any comments/ideas. (in branch cfranken but being pulled into Master right now)

**Comment by rafaqz** [comment]
Sorry I didn't have time to look at this at the time. But structurally things are looking amazing now - especially splitting things out into separate packages. They should be widely useful for ecologists in unrelated work. This is best in class, really exciting to see.

I wont release Photosynthesis.jl now because the modular package @Yujie-W is writing should probably have the name. I've mostly moved into spatial modelling and simulation so haven't put much time into photosynthesis/ecophys related things. But I'm glad you found some useful ideas in Photosynthesis.jl,
