### ISSUE TITLE
Integration over wavelength

### ISSUE THREAD

**Issue by zmoon** [CliMA/Land#33]
Given the way the wavelengths and wavelength band/bin widths are defined,

https://github.com/CliMA/Land/blob/dadb3a9f7924409bb9b1f8671652e6017b931016/src/CanopyLayers/types/wavelength.jl#L29-L35

and the `fast∫` definition, it seems to be set up for left Riemann sum. If you define the included bands this way (both bounds inclusive),

https://github.com/CliMA/Land/blob/dadb3a9f7924409bb9b1f8671652e6017b931016/src/CanopyLayers/types/wavelength.jl#L46-L47

extra energy is included in the integral, since the 700.0 nm band has its left edge at 700.0 but right edge at 705.0.

**Comment by Yujie-W** [comment]
If you dig up into the code more, you will find that
```
sWL = [400, 410, 420, ..., 640, 650, 655, 660, ..., 690, 695, 700, 705, ...]
dWL = [10, 10, 10, ..., 5, 5, 5, ...]
WL  = [405, 415, ..., 645, 652.5, 657.5, ..., 692.5, 697.5, 702.5, ...]
```
and PAR covers the range from 400 to 700 nm, namely the bin of WL from 405 to 697.5 nm.

**Comment by zmoon** [comment]
Ah, ok, so it moves to bin centers, in `CanopyLayers/initialize/leafopticals.jl`? Sorry I couldn't find that part when I was browsing.

**Comment by zmoon** [comment]
> Ah, ok, so it moves to bin centers, in `CanopyLayers/initialize/leafopticals.jl`?

@Yujie-W is this interpretation/attribution correct? Just want to confirm. Thanks for the assistance.

**Comment by Yujie-W** [comment]
> > Ah, ok, so it moves to bin centers, in `CanopyLayers/initialize/leafopticals.jl`?
> 
> @Yujie-W is this interpretation/attribution correct? Just want to confirm. Thanks for the assistance.

Yes.
