### ISSUE TITLE
Two land packages need adjustment: RootHydraulics error

### ISSUE THREAD

**Issue by waywardpidgeon** [CliMA/Land#58]
I ran the test suite for each of the Land packages and discovered that the field SH was 
removed from RootHydraulics on 20th October 2022. This gave rise to 5 errors (I.e. a
missing field SH) in the test set for PlantHydraulics and 2 for SoilPlantAirContinuum. 

Other than this error type, the test set for all of the packages ran without error.

This looks easy to fix, but I will leave it to the experts since I'm relatively new to CliMA.
6th April 2023

**Comment by Yujie-W** [comment]
Note that Land v0.2 is still under development and not yet tested intensively, and there would be many other changes not yet synced to main branch. So you will probbaly need to change your code accordingly. If your code was based on v0.1, please use the branch accordingly. You may want to post the code and versions to get the problem resoved.

1. CanopyLayers is deprecated in v0.2, CanopyRadiativeTransfer is used in v0.2
2. SH duplicates that in SOIL, so I removed it. The layout is number of soil layers can be more than root layers, so there is a ROOT_INDEX in a spac. By default, ROOT_INDEX is 1:N, corresponding to 1-N of the soil layers.

https://github.com/CliMA/Land/blob/ea005fb74e61965f4e52c47f2720529b172d341f/packages/ClimaCache.jl/src/spac/spac.jl#L114

But this can be customized to 2:N+1, meaning that root begins from second layer of the soil.

So the best way to find corresponding soil hydraulics you want is from `spac.SOIL.LAYERS[spac.ROOTS_INDEX[i]].`, where i is the ith root from top to bottom. For instance 
https://github.com/CliMA/Land/blob/ea005fb74e61965f4e52c47f2720529b172d341f/packages/PlantHydraulics.jl/src/pressure_profile.jl#L578-L583

**Comment by waywardpidgeon** [comment]
Thanks for that. I ran the for PlantHydraulics,using its development version, and it succeeded. 

For the dev version of SoilPlantAirContinuum, runtests.jl failed with undefined variables CNPP, GPP, PPAR, T_VEG. 

However, since I am carrying out a preliminary investigation into the Land system, and, as you say, v0.2 is still under development, I can wait till later so am closing the issue.

**Comment by Yujie-W** [comment]
FYI, most (maybe all) of the functions are set to private at this moment, so you need to use the functions like SoilPlantAirContinuum.GPP (the function GPP is not exported as a public function). Or you state it before use, such as
```
using Land.SoilPlantAirContinuum: GPP
```

**Comment by waywardpidgeon** [comment]
Thanks. Do I need to add that type of instruction to runtests.jl in the
Soil... subdirectory and an export instruction in quantity.jl where GPP etc
are defined?  Neither made the error go away. The prefix Land. gives an
error since it is not a package (I believe).

Sorry about these elementary questions! But if I change quantity.jl (by say
adding a using ... instruction), does it automatically get included. When I
try to do this manually it can't expand the macro @unpack.

Cheers - Kevin
