### ISSUE TITLE
CanopyLayers test missing functions

### ISSUE THREAD

**Issue by waywardpidgeon** [CliMA/Land#59]
Oh, I forgot to mention the CanopyLayers test. It seems to be incomplete having no associated use packages statement and then no knowing where to find structures/functions such as big_leaf_partition. I noted that it was missing from the list of packages in the 
runtests.jl top-level file, which I think includes all the other packages. I seem to be missing something here!

Cheers - Kevin

**Comment by Yujie-W** [comment]
See the comments in another thread, CanopyLayers is discontinued in v0.2
